export const TOTAL_CARDS = 144;

export const ANIMATION_DURATION = 1000;

export const DECK_STACKING_OFFSET = 0.5;

export const CARD_FRAME_IDS = [
	"card_clubs_02" as const,
	"card_clubs_03" as const,
	"card_clubs_04" as const,
	"card_clubs_05" as const,
	"card_clubs_06" as const,
	"card_clubs_07" as const,
	"card_clubs_08" as const,
	"card_clubs_09" as const,
	"card_clubs_10" as const,
	"card_clubs_A" as const,
	"card_clubs_J" as const,
	"card_clubs_K" as const,
	"card_clubs_Q" as const,
	"card_diamonds_02" as const,
	"card_diamonds_03" as const,
	"card_diamonds_04" as const,
	"card_diamonds_05" as const,
	"card_diamonds_06" as const,
	"card_diamonds_07" as const,
	"card_diamonds_08" as const,
	"card_diamonds_09" as const,
	"card_diamonds_10" as const,
	"card_diamonds_A" as const,
	"card_diamonds_J" as const,
	"card_diamonds_K" as const,
	"card_diamonds_Q" as const,
	"card_hearts_02" as const,
	"card_hearts_03" as const,
	"card_hearts_04" as const,
	"card_hearts_05" as const,
	"card_hearts_06" as const,
	"card_hearts_07" as const,
	"card_hearts_08" as const,
	"card_hearts_09" as const,
	"card_hearts_10" as const,
	"card_hearts_A" as const,
	"card_hearts_J" as const,
	"card_hearts_K" as const,
	"card_hearts_Q" as const,
	"card_joker_black" as const,
	"card_joker_red" as const,
	"card_spades_02" as const,
	"card_spades_03" as const,
	"card_spades_04" as const,
	"card_spades_05" as const,
	"card_spades_06" as const,
	"card_spades_07" as const,
	"card_spades_08" as const,
	"card_spades_09" as const,
	"card_spades_10" as const,
	"card_spades_A" as const,
	"card_spades_J" as const,
	"card_spades_K" as const,
	"card_spades_Q" as const,
] as const;
